import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ContentReveal from "@/components/ContentReveal";
import NumericPreloader from "@/components/NumericPreloader";

const interTight = localFont({
  src: [
    {
      path: "../public/fonts/InterTight-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/InterTight-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/InterTight-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/InterTight-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-geist-sans",
});

export const metadata: Metadata = {
  title: "Cosmorrow - journey into the Future of the Universe",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interTight.className} ${interTight.variable} antialiased`}>
        <NumericPreloader />
        <ContentReveal>{children}</ContentReveal>
      </body>
    </html>
  );
}
